apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flink-config
  labels:
    app: {{ .Release.Name }}-flink
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: {{ .Release.Name }}-flink-jobmanager
    taskmanager.numberOfTaskSlots: 1
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    jobmanager.heap.size: 1024m
    taskmanager.memory.process.size: 10240m
    jobmanager.heap.size: 5120m
    taskmanager.memory.jvm-overhead.fraction: 0.8
    classloader.resolve-order: parent-first
    containerized.taskmanager.env.MINIO_HOST: /usr/lib/native
    containerized.taskmanager.env.MINIO_ACCESS_KEY: /usr/lib/native
    containerized.taskmanager.env.MINIO_SECRET_KEY: /usr/lib/native
    containerized.taskmanager.env.MINIO_BUCKET_IMPORT: /usr/lib/native
    containerized.taskmanager.env.MINIO_BUCKET_MODELS: /usr/lib/native
    containerized.taskmanager.env.MINIO_BUCKET_SCHEMA: /usr/lib/native
    containerized.taskmanager.env.KAFKA_HOST: /usr/lib/native
    containerized.taskmanager.env.KAFKA_DATA_TOPIC: /usr/lib/native
    containerized.taskmanager.env.MODEL_PUBLISHED_TOPIC: /usr/lib/native
    containerized.taskmanager.env.MODEL_DEPLOYED_TOPIC: /usr/lib/native
    containerized.taskmanager.env.PREDICTIONS_TOPIC: /usr/lib/native
    containerized.taskmanager.env.IMPORT_TOPIC: /usr/lib/native
    containerized.taskmanager.env.RAW_SENSOR_DATA_TOPIC: /usr/lib/native
    containerized.taskmanager.env.SENSOR_DATA_TOPIC: /usr/lib/native
  log4j.properties: |+
    log4j.rootLogger=INFO, file
    log4j.logger.akka=INFO
    log4j.logger.org.apache.kafka=INFO
    log4j.logger.org.apache.hadoop=INFO
    log4j.logger.org.apache.zookeeper=INFO
    log4j.appender.file=org.apache.log4j.FileAppender
    log4j.appender.file.file=${log.file}
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    log4j.logger.org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline=ERROR, file