minio: 
  persistence: 
    enabled: true
    storageClass: refit
    size: 100Gi

kafka: 
  replicaCount: 2
  autoCreateTopicsEnable: true
  nodeSelector:
    refit: enabled
  persistence:
    enabled: true
    storageClass: refit
    size: 100Gi
  resources:
    limits:
      memory: "1000Mi"
    requests:
      memory: "500Mi"
  zookeeper:
    persistence:
      enabled: true
      storageClass: refit
    nodeSelector:
      refit: enabled

cassandra: 
  replicaCount: 6
  cluster:
    seedCount: 6
  persistence:
    enabled: true
    storageClass: refit
    size: 100Gi
  nodeSelector: 
    refit: enabled
  dbUser:
    user: cassandra
  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "5000Mi"

postgresql:
  persistence: 
    enabled: true
    storageClass: refit
    size: 100Gi
  primary: 
    nodeSelector: 
      refit: enabled  
  resources:
    limits:
      memory: "4000Mi"
    requests:
      memory: "1000Mi"

grafana: 
  persistence:
    storageClass: refit
    size: 100Gi
    enabled: true
  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "5000Mi"
  nodeSelector:
    refit: enabled
  admin: 
    password: refit
    user: refit

flink: 
  flinkVersion: 1.10.1
  scalaVersion: 2.11
  nodeSelector:
    refit: enabled
  jobManager: 
    limits: 
      memory: "10000Mi"
    requests: 
      memory: "5000Mi"
  taskManager: 
    replicas: 6
    limits: 
      memory: "15000Mi"
    requests: 
      memory: "6000Mi"

refit:
  nodeSelector:
    refit: enabled
  integrations:
    replicas: 1
  ingestion: 
    replicas: 1
  notebook:
    replicas: 1
    resources:
      limits:
        memory: "10000Mi"
      requests:
        memory: "5000Mi"
