minio: 
  persistence: 
    enabled: false

cassandra:
  image:
    repository: cdliotprototype/cdl-refit-cassandra
    tag: BETA-0.14
  cluster:
    replicaCount: 1
    seedCount: 1
  persistence:
    enabled: false
  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "3000Mi"
  dbUser:
    existingSecret: refit-cassandra-credentials

  cluster: 
    slaveCount: 2
  metrics:
    enabled: false

  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "3000Mi"

grafana: 
  nodeSelector:
    coredns: enabled
  persistence:
    enabled: false
  env:
    GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,simpod-json-datasource
  plugins:
    - name:
      value: grafana-simple-json-datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: REFIT
        type: simpod-json-datasource
        url: http://refit-integrations:3000
        isDefault: true
        jsonData:
          tlsSkipVerify: true
  sidecar:
    dashboards:
      enabled: true

flink: 
  flinkVersion: 1.10.1
  scalaVersion: 2.11
  nodeSelector:
    coredns: enabled
  jobManager: 
    limits: 
      memory: "5000Mi"
    requests: 
      memory: "2000Mi"
  taskManager: 
    replicas: 1
    limits: 
      memory: "5000Mi"
    requests: 
      memory: "2000Mi"
pulsar:
  pulsarVersion: 2.6.0
  nodeSelector:
    coredns: enabled
  resources: 
    limits: 
      memory: "10000Mi"
    requests: 
      memory: "3000Mi"

refit: 
  version: BETA-0.14
  encryptionKey: __generated__
  cassandraPassword: __generated__
  nodeSelector:
    coredns: enabled
  integrations:
    replicas: 1
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "500Mi"
  notebook:
    replicas: 1
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "500Mi"
  ingestion:
    replicas: 1
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "500Mi"
  schemaConfigMap: __demo__
